# Generated by Django 4.0 on 2022-11-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_quantity',
        ),
    ]
