# Generated by Django 4.0 on 2022-11-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_cart_updated_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='addcart_by',
        ),
    ]
