# Generated by Django 4.0 on 2022-11-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_cart_addcart_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='transactionid',
        ),
    ]
